"""informe: usuarios, api keys, subject, reports, comparables y eventos

Revision ID: cf54ac6bc9a5
Revises: 1e4a025d6104
Create Date: 2026-08-13 20:58:06.329659

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "cf54ac6bc9a5"
down_revision: str | None = "1e4a025d6104"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), server_default=sa.text("'agent'"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role in ('owner', 'admin', 'agent', 'viewer')", name=op.f("ck_users_role")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["core.organizations.id"], name=op.f("fk_users_org_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("org_id", "email", name="user_email_unique"),
        schema="core",
    )
    op.create_index("idx_users_org", "users", ["org_id", "active"], unique=False, schema="core")
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("prefix", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["core.users.id"],
            name=op.f("fk_api_keys_created_by"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["core.organizations.id"],
            name=op.f("fk_api_keys_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name="api_key_hash_unique"),
        schema="core",
    )
    op.create_index(
        "idx_api_keys_org", "api_keys", ["org_id", "revoked_at"], unique=False, schema="core"
    )
    op.create_table(
        "subject_properties",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("external_ref", sa.Text(), nullable=True),
        sa.Column("address_raw", sa.Text(), nullable=False),
        sa.Column("street", sa.Text(), nullable=True),
        sa.Column("street_number", sa.Text(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("neighborhood_id", sa.UUID(), nullable=True),
        sa.Column("city", sa.Text(), server_default=sa.text("'CABA'"), nullable=False),
        sa.Column("province", sa.Text(), server_default=sa.text("'CABA'"), nullable=False),
        sa.Column("lat", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("lng", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("geocode_source", sa.Text(), nullable=True),
        sa.Column("geocode_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("property_type", sa.Text(), nullable=False),
        sa.Column("rooms", sa.SmallInteger(), nullable=True),
        sa.Column("bedrooms", sa.SmallInteger(), nullable=True),
        sa.Column("bathrooms", sa.SmallInteger(), nullable=True),
        sa.Column("surface_total", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("surface_covered", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("age_years", sa.SmallInteger(), nullable=True),
        sa.Column("floor_number", sa.SmallInteger(), nullable=True),
        sa.Column("has_elevator", sa.Boolean(), nullable=True),
        sa.Column("condition", sa.Text(), nullable=True),
        sa.Column("orientation", sa.Text(), nullable=True),
        sa.Column(
            "amenities", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False
        ),
        sa.Column("parking_spaces", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("expenses_ars", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition is null or condition in ('a_estrenar', 'excelente', 'muy_bueno', 'bueno', 'a_refaccionar')",
            name=op.f("ck_subject_properties_condition"),
        ),
        sa.CheckConstraint(
            "geocode_source is null or geocode_source in ('NOMINATIM', 'GOOGLE', 'MANUAL', 'NONE')",
            name=op.f("ck_subject_properties_geocode_source"),
        ),
        sa.CheckConstraint(
            "orientation is null or orientation in ('frente', 'contrafrente', 'lateral', 'interno')",
            name=op.f("ck_subject_properties_orientation"),
        ),
        sa.CheckConstraint(
            "property_type in ('departamento', 'casa', 'ph')",
            name=op.f("ck_subject_properties_property_type"),
        ),
        sa.CheckConstraint(
            "age_years is null or age_years between 0 and 200",
            name=op.f("ck_subject_properties_age_rango"),
        ),
        sa.CheckConstraint(
            "bathrooms is null or bathrooms between 0 and 10",
            name=op.f("ck_subject_properties_bathrooms_rango"),
        ),
        sa.CheckConstraint(
            "bedrooms is null or bedrooms between 0 and 12",
            name=op.f("ck_subject_properties_bedrooms_rango"),
        ),
        sa.CheckConstraint(
            "rooms is null or rooms between 1 and 15",
            name=op.f("ck_subject_properties_rooms_rango"),
        ),
        sa.CheckConstraint(
            "surface_covered is null or surface_covered > 0",
            name=op.f("ck_subject_properties_surface_covered_pos"),
        ),
        sa.CheckConstraint(
            "surface_covered is null or surface_total is null or surface_covered <= surface_total",
            name=op.f("ck_subject_properties_surface_coherente"),
        ),
        sa.CheckConstraint(
            "surface_total is null or surface_total > 0",
            name=op.f("ck_subject_properties_surface_total_pos"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["core.users.id"],
            name=op.f("fk_subject_properties_created_by"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["neighborhood_id"],
            ["corpus.neighborhoods.id"],
            name=op.f("fk_subject_properties_neighborhood_id"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["core.organizations.id"],
            name=op.f("fk_subject_properties_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subject_properties")),
        schema="core",
    )
    op.create_index(
        "idx_subject_properties_external",
        "subject_properties",
        ["org_id", "external_ref"],
        unique=False,
        schema="core",
        postgresql_where="external_ref is not null",
    )
    op.create_index(
        "idx_subject_properties_org",
        "subject_properties",
        ["org_id", "created_at"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("subject_property_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'QUEUED'"), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column("requested_via", sa.Text(), server_default=sa.text("'UI'"), nullable=False),
        sa.Column("engine_version", sa.Text(), nullable=False),
        sa.Column("prompt_bundle_version", sa.Text(), nullable=False),
        sa.Column("method_version", sa.Text(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column("value_low", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("value_mid", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("value_high", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("closing_low", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("closing_high", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("price_per_m2", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("weighted_surface", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("comparables_used", sa.SmallInteger(), nullable=True),
        sa.Column("comparables_found", sa.SmallInteger(), nullable=True),
        sa.Column("dispersion", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("confidence", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("narrative_md", sa.Text(), nullable=True),
        sa.Column(
            "methodology",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("insufficient_reason", sa.Text(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "critic_rejections", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("tokens_in", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tokens_out", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence is null or confidence in ('ALTA', 'MEDIA', 'BAJA')",
            name=op.f("ck_reports_confidence"),
        ),
        sa.CheckConstraint(
            "currency is null or currency in ('USD', 'ARS')", name=op.f("ck_reports_currency")
        ),
        sa.CheckConstraint("requested_via in ('UI', 'API')", name=op.f("ck_reports_requested_via")),
        sa.CheckConstraint(
            "status <> 'INSUFFICIENT_DATA' or insufficient_reason is not null",
            name=op.f("ck_reports_insufficient_tiene_razon"),
        ),
        sa.CheckConstraint(
            "status <> 'SUCCEEDED' or (value_low is not null and value_mid is not null and value_high is not null and value_low <= value_mid and value_mid <= value_high)",
            name=op.f("ck_reports_valores_coherentes"),
        ),
        sa.CheckConstraint(
            "status in ('QUEUED', 'RUNNING', 'SUCCEEDED', 'INSUFFICIENT_DATA', 'FAILED', 'CANCELLED')",
            name=op.f("ck_reports_status"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["core.organizations.id"],
            name=op.f("fk_reports_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["core.users.id"],
            name=op.f("fk_reports_requested_by"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subject_property_id"],
            ["core.subject_properties.id"],
            name=op.f("fk_reports_subject_property_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        schema="core",
    )
    op.create_index(
        "idx_reports_idempotency",
        "reports",
        ["org_id", "idempotency_key"],
        unique=True,
        schema="core",
        postgresql_where="idempotency_key is not null",
    )
    op.create_index(
        "idx_reports_org_lista", "reports", ["org_id", "created_at"], unique=False, schema="core"
    )
    op.create_index(
        "idx_reports_status",
        "reports",
        ["status"],
        unique=False,
        schema="core",
        postgresql_where="status in ('QUEUED','RUNNING')",
    )
    op.create_index(
        "idx_reports_subject",
        "reports",
        ["subject_property_id", "created_at"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "report_artifacts",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("pdf_path", sa.Text(), nullable=False),
        sa.Column("pdf_bytes", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("template_version", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["core.reports.id"],
            name=op.f("fk_report_artifacts_report_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("report_id", name=op.f("pk_report_artifacts")),
        schema="core",
    )
    op.create_table(
        "report_comparables",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("included", sa.Boolean(), nullable=False),
        sa.Column("exclusion_reason", sa.Text(), nullable=True),
        sa.Column("similarity_score", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("distance_m", sa.Integer(), nullable=True),
        sa.Column("snapshot_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("snapshot_currency", sa.Text(), nullable=False),
        sa.Column("snapshot_surface", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("raw_price_per_m2", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "adjustments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("adjusted_price_per_m2", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "snapshot_currency in ('USD', 'ARS')",
            name=op.f("ck_report_comparables_snapshot_currency"),
        ),
        sa.CheckConstraint(
            "included or exclusion_reason is not null",
            name=op.f("ck_report_comparables_excluido_tiene_razon"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["corpus.listings.id"],
            name=op.f("fk_report_comparables_listing_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["core.reports.id"],
            name=op.f("fk_report_comparables_report_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_comparables")),
        sa.UniqueConstraint("report_id", "listing_id", name="report_comp_unico"),
        schema="core",
    )
    op.create_index(
        "idx_report_comparables_report",
        "report_comparables",
        ["report_id", "included"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "report_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.SmallInteger(), nullable=False),
        sa.Column("node", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("trace_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('STARTED', 'OK', 'RETRIED', 'FAILED', 'SKIPPED')",
            name=op.f("ck_report_events_status"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["core.reports.id"],
            name=op.f("fk_report_events_report_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_events")),
        schema="core",
    )
    op.create_index(
        "idx_report_events_report",
        "report_events",
        ["report_id", "seq"],
        unique=False,
        schema="core",
    )
    op.create_foreign_key(
        op.f("fk_ingest_items_listing_id"),
        "ingest_items",
        "listings",
        ["listing_id"],
        ["id"],
        source_schema="corpus",
        referent_schema="corpus",
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_listing_clusters_canonical_id",
        "listing_clusters",
        "listings",
        ["canonical_id"],
        ["id"],
        source_schema="corpus",
        referent_schema="corpus",
        ondelete="SET NULL",
        use_alter=True,
    )
    # NO se borra idx_listing_embeddings_hnsw. El autogenerate lo propuso
    # porque el índice se crea con SQL crudo en la migración anterior (pgvector
    # HNSW no se puede expresar en la metadata del ORM) y por lo tanto Alembic
    # lo ve como "un índice que sobra". Es al revés: es el índice que hace
    # viable la búsqueda por embedding del nodo 2. Aceptar el autogenerate a
    # ciegas acá habría roto el kNN sin que ningún test lo notara.
    op.create_foreign_key(
        op.f("fk_listings_created_by"),
        "listings",
        "users",
        ["created_by"],
        ["id"],
        source_schema="corpus",
        referent_schema="core",
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_listings_verified_by"),
        "listings",
        "users",
        ["verified_by"],
        ["id"],
        source_schema="corpus",
        referent_schema="core",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_listings_verified_by"), "listings", schema="corpus", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_listings_created_by"), "listings", schema="corpus", type_="foreignkey"
    )
    # Simétrico del upgrade: el índice HNSW no se tocó al subir, así que
    # tampoco se recrea al bajar.
    op.drop_constraint(
        "fk_listing_clusters_canonical_id", "listing_clusters", schema="corpus", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_ingest_items_listing_id"), "ingest_items", schema="corpus", type_="foreignkey"
    )
    op.drop_index("idx_report_events_report", table_name="report_events", schema="core")
    op.drop_table("report_events", schema="core")
    op.drop_index("idx_report_comparables_report", table_name="report_comparables", schema="core")
    op.drop_table("report_comparables", schema="core")
    op.drop_table("report_artifacts", schema="core")
    op.drop_index("idx_reports_subject", table_name="reports", schema="core")
    op.drop_index(
        "idx_reports_status",
        table_name="reports",
        schema="core",
        postgresql_where="status in ('QUEUED','RUNNING')",
    )
    op.drop_index("idx_reports_org_lista", table_name="reports", schema="core")
    op.drop_index(
        "idx_reports_idempotency",
        table_name="reports",
        schema="core",
        postgresql_where="idempotency_key is not null",
    )
    op.drop_table("reports", schema="core")
    op.drop_index("idx_subject_properties_org", table_name="subject_properties", schema="core")
    op.drop_index(
        "idx_subject_properties_external",
        table_name="subject_properties",
        schema="core",
        postgresql_where="external_ref is not null",
    )
    op.drop_table("subject_properties", schema="core")
    op.drop_index("idx_api_keys_org", table_name="api_keys", schema="core")
    op.drop_table("api_keys", schema="core")
    op.drop_index("idx_users_org", table_name="users", schema="core")
    op.drop_table("users", schema="core")
    # ### end Alembic commands ###
