"""corpus inicial

Revision ID: 1e4a025d6104
Revises:
Create Date: 2026-08-13 14:39:57.330027

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = "1e4a025d6104"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column(
            "timezone",
            sa.Text(),
            server_default=sa.text("'America/Argentina/Buenos_Aires'"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "monthly_report_quota", sa.Integer(), server_default=sa.text("200"), nullable=False
        ),
        sa.Column(
            "fetch_budget_monthly", sa.Integer(), server_default=sa.text("2000"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
        schema="core",
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'RUNNING'"), nullable=False),
        sa.Column("discovered", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("fetched", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("skipped", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("blocked", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("errors", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "mode in ('DISCOVER', 'FETCH', 'BACKFILL', 'ONDEMAND')",
            name=op.f("ck_ingest_runs_mode"),
        ),
        sa.CheckConstraint(
            "status in ('RUNNING', 'OK', 'PARTIAL', 'FAILED')", name=op.f("ck_ingest_runs_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_runs")),
        schema="corpus",
    )
    op.create_table(
        "listing_clusters",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("canonical_id", sa.UUID(), nullable=True),
        sa.Column("member_count", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("match_method", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_method in ('EXACT_ADDR', 'FUZZY', 'EMBEDDING', 'LLM', 'MANUAL')",
            name=op.f("ck_listing_clusters_match_method"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_clusters")),
        schema="corpus",
    )
    op.create_table(
        "neighborhoods",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("province", sa.Text(), nullable=False),
        sa.Column(
            "aliases", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False
        ),
        sa.Column("badata_key", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("centroid_lat", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("centroid_lng", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["corpus.neighborhoods.id"], name=op.f("fk_neighborhoods_parent_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_neighborhoods")),
        sa.UniqueConstraint("city", "name", name="neighborhood_unique"),
        schema="corpus",
    )
    op.create_index(
        "idx_neighborhoods_aliases",
        "neighborhoods",
        ["aliases"],
        unique=False,
        schema="corpus",
        postgresql_using="gin",
    )
    op.create_table(
        "inventory_properties",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.Text(), server_default=sa.text("'PANEL'"), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("address_raw", sa.Text(), nullable=True),
        sa.Column("neighborhood_id", sa.UUID(), nullable=True),
        sa.Column("neighborhood_label", sa.Text(), nullable=True),
        sa.Column("property_type", sa.Text(), nullable=True),
        sa.Column("operation", sa.Text(), nullable=True),
        sa.Column("rooms", sa.SmallInteger(), nullable=True),
        sa.Column("surface_total", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("surface_covered", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=True),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["neighborhood_id"],
            ["corpus.neighborhoods.id"],
            name=op.f("fk_inventory_properties_neighborhood_id"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["core.organizations.id"],
            name=op.f("fk_inventory_properties_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_properties")),
        sa.UniqueConstraint("org_id", "source", "source_id", name="inventory_source_unique"),
        schema="core",
    )
    op.create_table(
        "ingest_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("http_status", sa.SmallInteger(), nullable=True),
        sa.Column("listing_id", sa.UUID(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('OK', 'BLOCKED', 'PARSE_ERROR', 'SKIPPED_CACHE', 'HTTP_ERROR', 'SKIPPED_ROBOTS')",
            name=op.f("ck_ingest_items_status"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["corpus.ingest_runs.id"],
            name=op.f("fk_ingest_items_run_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_items")),
        schema="corpus",
    )
    op.create_index(
        "idx_ingest_items_run", "ingest_items", ["run_id", "status"], unique=False, schema="corpus"
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("operation", sa.Text(), server_default=sa.text("'SALE'"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("raw_html_path", sa.Text(), nullable=True),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column(
            "price_on_request", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("address_raw", sa.Text(), nullable=True),
        sa.Column("neighborhood_id", sa.UUID(), nullable=True),
        sa.Column("neighborhood_label", sa.Text(), nullable=True),
        sa.Column("lat", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("lng", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("publisher", sa.Text(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delisted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cluster_id", sa.UUID(), nullable=True),
        sa.Column(
            "quality_flags",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "currency is null or currency in ('USD', 'ARS')", name=op.f("ck_listings_currency")
        ),
        sa.CheckConstraint("operation in ('SALE', 'RENT')", name=op.f("ck_listings_operation")),
        sa.CheckConstraint(
            "source in ('PORTAL_A', 'PORTAL_B', 'MELI', 'CRM', 'PANEL', 'BADATA', 'PROPERATI', 'MANUAL', 'PASTED')",
            name=op.f("ck_listings_source"),
        ),
        sa.CheckConstraint(
            "source not in ('MANUAL','PASTED') or org_id is not null",
            name=op.f("ck_listings_manual_tiene_org"),
        ),
        sa.CheckConstraint("price is null or price > 0", name=op.f("ck_listings_price_positivo")),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["corpus.listing_clusters.id"],
            name=op.f("fk_listings_cluster_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["neighborhood_id"],
            ["corpus.neighborhoods.id"],
            name=op.f("fk_listings_neighborhood_id"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["core.organizations.id"],
            name=op.f("fk_listings_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
        sa.UniqueConstraint("source", "source_id", name="listings_source_unique"),
        schema="corpus",
    )
    op.create_index(
        "idx_listings_addr_trgm",
        "listings",
        ["address_raw"],
        unique=False,
        schema="corpus",
        postgresql_using="gin",
        postgresql_ops={"address_raw": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_listings_cluster",
        "listings",
        ["cluster_id"],
        unique=False,
        schema="corpus",
        postgresql_where="cluster_id is not null",
    )
    op.create_index(
        "idx_listings_neigh",
        "listings",
        ["neighborhood_id", "active", "published_at"],
        unique=False,
        schema="corpus",
    )
    op.create_index(
        "idx_listings_org",
        "listings",
        ["org_id"],
        unique=False,
        schema="corpus",
        postgresql_where="org_id is not null",
    )
    op.create_index(
        "idx_listings_stale",
        "listings",
        ["last_seen_at"],
        unique=False,
        schema="corpus",
        postgresql_where="active",
    )
    op.create_table(
        "market_index",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("neighborhood_id", sa.UUID(), nullable=True),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("property_type", sa.Text(), nullable=False),
        sa.Column("rooms", sa.SmallInteger(), nullable=True),
        sa.Column("condition_group", sa.Text(), nullable=True),
        sa.Column("usd_per_m2", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "condition_group is null or condition_group in ('usado', 'a_estrenar', 'todos')",
            name=op.f("ck_market_index_condition_group"),
        ),
        sa.CheckConstraint(
            "source in ('BADATA', 'PROPERATI', 'INTERNAL')", name=op.f("ck_market_index_source")
        ),
        sa.ForeignKeyConstraint(
            ["neighborhood_id"],
            ["corpus.neighborhoods.id"],
            name=op.f("fk_market_index_neighborhood_id"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_index")),
        sa.UniqueConstraint(
            "neighborhood_id",
            "period",
            "property_type",
            "rooms",
            "condition_group",
            "source",
            name="market_index_unique",
        ),
        schema="corpus",
    )
    op.create_table(
        "listing_embeddings",
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1024), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["corpus.listings.id"],
            name=op.f("fk_listing_embeddings_listing_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("listing_id", name=op.f("pk_listing_embeddings")),
        schema="corpus",
    )
    op.create_table(
        "listing_features",
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("property_type", sa.Text(), nullable=True),
        sa.Column("rooms", sa.SmallInteger(), nullable=True),
        sa.Column("bedrooms", sa.SmallInteger(), nullable=True),
        sa.Column("bathrooms", sa.SmallInteger(), nullable=True),
        sa.Column("surface_total", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("surface_covered", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("floor_number", sa.SmallInteger(), nullable=True),
        sa.Column("age_years", sa.SmallInteger(), nullable=True),
        sa.Column("condition", sa.Text(), nullable=True),
        sa.Column("orientation", sa.Text(), nullable=True),
        sa.Column("has_elevator", sa.Boolean(), nullable=True),
        sa.Column("parking_spaces", sa.SmallInteger(), nullable=True),
        sa.Column("balcony", sa.Boolean(), nullable=True),
        sa.Column(
            "amenities", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False
        ),
        sa.Column("expenses_ars", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("credit_eligible", sa.Boolean(), nullable=True),
        sa.Column("extractor_model", sa.Text(), nullable=False),
        sa.Column("extractor_version", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("needs_review", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "extracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition is null or condition in ('a_estrenar', 'excelente', 'muy_bueno', 'bueno', 'a_refaccionar')",
            name=op.f("ck_listing_features_condition"),
        ),
        sa.CheckConstraint(
            "orientation is null or orientation in ('frente', 'contrafrente', 'lateral', 'interno')",
            name=op.f("ck_listing_features_orientation"),
        ),
        sa.CheckConstraint(
            "property_type is null or property_type in ('departamento', 'casa', 'ph', 'local', 'oficina', 'cochera', 'terreno', 'galpon', 'otro')",
            name=op.f("ck_listing_features_property_type"),
        ),
        sa.CheckConstraint(
            "rooms is null or rooms between 1 and 20", name=op.f("ck_listing_features_rooms_rango")
        ),
        sa.CheckConstraint(
            "surface_total is null or surface_total > 0",
            name=op.f("ck_listing_features_surface_positiva"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["corpus.listings.id"],
            name=op.f("fk_listing_features_listing_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("listing_id", name=op.f("pk_listing_features")),
        schema="corpus",
    )
    op.create_index(
        "idx_listing_features_match",
        "listing_features",
        ["property_type", "rooms", "surface_covered"],
        unique=False,
        schema="corpus",
    )
    op.create_table(
        "listing_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["corpus.listings.id"],
            name=op.f("fk_listing_snapshots_listing_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_snapshots")),
        schema="corpus",
    )
    op.create_index(
        "idx_listing_snapshots_time",
        "listing_snapshots",
        ["listing_id", "observed_at"],
        unique=False,
        schema="corpus",
    )
    # ### end Alembic commands ###

    # --- Añadido a mano: autogenerate no genera índices HNSW ---
    # HNSW sobre IVFFlat: mejor recall/latencia a esta escala y no hay que
    # reentrenar al crecer el corpus (doc 01, ADR-004).
    op.execute(
        "CREATE INDEX idx_listing_embeddings_hnsw ON corpus.listing_embeddings "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS corpus.idx_listing_embeddings_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_listing_snapshots_time", table_name="listing_snapshots", schema="corpus")
    op.drop_table("listing_snapshots", schema="corpus")
    op.drop_index("idx_listing_features_match", table_name="listing_features", schema="corpus")
    op.drop_table("listing_features", schema="corpus")
    op.drop_table("listing_embeddings", schema="corpus")
    op.drop_table("market_index", schema="corpus")
    op.drop_index(
        "idx_listings_stale", table_name="listings", schema="corpus", postgresql_where="active"
    )
    op.drop_index(
        "idx_listings_org",
        table_name="listings",
        schema="corpus",
        postgresql_where="org_id is not null",
    )
    op.drop_index("idx_listings_neigh", table_name="listings", schema="corpus")
    op.drop_index(
        "idx_listings_cluster",
        table_name="listings",
        schema="corpus",
        postgresql_where="cluster_id is not null",
    )
    op.drop_index(
        "idx_listings_addr_trgm",
        table_name="listings",
        schema="corpus",
        postgresql_using="gin",
        postgresql_ops={"address_raw": "gin_trgm_ops"},
    )
    op.drop_table("listings", schema="corpus")
    op.drop_index("idx_ingest_items_run", table_name="ingest_items", schema="corpus")
    op.drop_table("ingest_items", schema="corpus")
    op.drop_table("inventory_properties", schema="core")
    op.drop_index(
        "idx_neighborhoods_aliases",
        table_name="neighborhoods",
        schema="corpus",
        postgresql_using="gin",
    )
    op.drop_table("neighborhoods", schema="corpus")
    op.drop_table("listing_clusters", schema="corpus")
    op.drop_table("ingest_runs", schema="corpus")
    op.drop_table("organizations", schema="core")
    # ### end Alembic commands ###
